name: Publish to npm
author: pascalgn
description: Automatically publish new versions to npm

inputs:
  commit_pattern:
    description: The pattern that matches version update commits.
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: blue
